// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// graph_as_matrix
List graph_as_matrix(SEXP phase_type_graph);
RcppExport SEXP _ptdalgorithms_graph_as_matrix(SEXP phase_type_graphSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type phase_type_graph(phase_type_graphSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_as_matrix(phase_type_graph));
    return rcpp_result_gen;
END_RCPP
}
// matrix_as_graph
SEXP matrix_as_graph(NumericVector initial_probability_vector, NumericMatrix subintensity_matrix, NumericMatrix rewards);
RcppExport SEXP _ptdalgorithms_matrix_as_graph(SEXP initial_probability_vectorSEXP, SEXP subintensity_matrixSEXP, SEXP rewardsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type initial_probability_vector(initial_probability_vectorSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type subintensity_matrix(subintensity_matrixSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type rewards(rewardsSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_as_graph(initial_probability_vector, subintensity_matrix, rewards));
    return rcpp_result_gen;
END_RCPP
}
// kingman_gen_graph
SEXP kingman_gen_graph(int n, int m);
RcppExport SEXP _ptdalgorithms_kingman_gen_graph(SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(kingman_gen_graph(n, m));
    return rcpp_result_gen;
END_RCPP
}
// reward_transform
SEXP reward_transform(SEXP phase_type_graph, Rcpp::Function reward_function);
RcppExport SEXP _ptdalgorithms_reward_transform(SEXP phase_type_graphSEXP, SEXP reward_functionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type phase_type_graph(phase_type_graphSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type reward_function(reward_functionSEXP);
    rcpp_result_gen = Rcpp::wrap(reward_transform(phase_type_graph, reward_function));
    return rcpp_result_gen;
END_RCPP
}
// reward_transform_by_reward
SEXP reward_transform_by_reward(SEXP phase_type_graph, int reward);
RcppExport SEXP _ptdalgorithms_reward_transform_by_reward(SEXP phase_type_graphSEXP, SEXP rewardSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type phase_type_graph(phase_type_graphSEXP);
    Rcpp::traits::input_parameter< int >::type reward(rewardSEXP);
    rcpp_result_gen = Rcpp::wrap(reward_transform_by_reward(phase_type_graph, reward));
    return rcpp_result_gen;
END_RCPP
}
// graph_exp_cov
List graph_exp_cov(SEXP phase_type_graph);
RcppExport SEXP _ptdalgorithms_graph_exp_cov(SEXP phase_type_graphSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type phase_type_graph(phase_type_graphSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_exp_cov(phase_type_graph));
    return rcpp_result_gen;
END_RCPP
}
// graph_info
List graph_info(SEXP phase_type_graph);
RcppExport SEXP _ptdalgorithms_graph_info(SEXP phase_type_graphSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type phase_type_graph(phase_type_graphSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_info(phase_type_graph));
    return rcpp_result_gen;
END_RCPP
}
// set_rewards
SEXP set_rewards(SEXP phase_type_graph, Rcpp::Function set_reward_function);
RcppExport SEXP _ptdalgorithms_set_rewards(SEXP phase_type_graphSEXP, SEXP set_reward_functionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type phase_type_graph(phase_type_graphSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type set_reward_function(set_reward_functionSEXP);
    rcpp_result_gen = Rcpp::wrap(set_rewards(phase_type_graph, set_reward_function));
    return rcpp_result_gen;
END_RCPP
}
// generate_graph
SEXP generate_graph(int state_length, Rcpp::Function initial, Rcpp::Function children, Rcpp::Function rewards_from_state);
RcppExport SEXP _ptdalgorithms_generate_graph(SEXP state_lengthSEXP, SEXP initialSEXP, SEXP childrenSEXP, SEXP rewards_from_stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type state_length(state_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type children(childrenSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type rewards_from_state(rewards_from_stateSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_graph(state_length, initial, children, rewards_from_state));
    return rcpp_result_gen;
END_RCPP
}
// graph_reduce
SEXP graph_reduce(SEXP phase_type_graph);
RcppExport SEXP _ptdalgorithms_graph_reduce(SEXP phase_type_graphSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type phase_type_graph(phase_type_graphSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_reduce(phase_type_graph));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ptdalgorithms_graph_as_matrix", (DL_FUNC) &_ptdalgorithms_graph_as_matrix, 1},
    {"_ptdalgorithms_matrix_as_graph", (DL_FUNC) &_ptdalgorithms_matrix_as_graph, 3},
    {"_ptdalgorithms_kingman_gen_graph", (DL_FUNC) &_ptdalgorithms_kingman_gen_graph, 2},
    {"_ptdalgorithms_reward_transform", (DL_FUNC) &_ptdalgorithms_reward_transform, 2},
    {"_ptdalgorithms_reward_transform_by_reward", (DL_FUNC) &_ptdalgorithms_reward_transform_by_reward, 2},
    {"_ptdalgorithms_graph_exp_cov", (DL_FUNC) &_ptdalgorithms_graph_exp_cov, 1},
    {"_ptdalgorithms_graph_info", (DL_FUNC) &_ptdalgorithms_graph_info, 1},
    {"_ptdalgorithms_set_rewards", (DL_FUNC) &_ptdalgorithms_set_rewards, 2},
    {"_ptdalgorithms_generate_graph", (DL_FUNC) &_ptdalgorithms_generate_graph, 4},
    {"_ptdalgorithms_graph_reduce", (DL_FUNC) &_ptdalgorithms_graph_reduce, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ptdalgorithms(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
