# Experiments

```{r}
library("tidyverse")
Rcpp::sourceCpp("experiments.cpp")
```

```{r}
rewardtransformparm <- function(rewards, initprob, subintensemat){
  d <- sum(rewards > 0)
  p <- length(initprob)
  qmat <- matrix(rep(0,p^2), ncol = p)
  for(i in 1:p){
    for(j in (1:p)[-i]){
      qmat[i,j] <- -subintensemat[i,j]/subintensemat[i,i]
    }
  }
  ##
  # If all rewards are stricly postive everything is simpler
  ##
  if(d == p){
    pmat <- qmat
    alphavec <- initprob
  }
  else{
    qplusplus <- qmat[(rewards > 0),(rewards > 0)]
    qpluszero <- qmat[(rewards > 0),(rewards == 0)]
    qzeroplus <- qmat[(rewards == 0),(rewards > 0)]
    qzerozero <- qmat[(rewards == 0 ), (rewards == 0)]
    pmat <- qplusplus + qpluszero %*% solve(diag(1, nrow = p-d)-qzerozero) %*% qzeroplus
    piplus <- initprob[(rewards > 0)]
    pizero <- initprob[(rewards == 0)]
    alphavec <- piplus + pizero %*% solve(diag(1, nrow = p-d)-qzerozero) %*% qzeroplus 
    subintensemat <- as.matrix(subintensemat[(rewards > 0), (rewards >0)])
    rewards <- rewards[rewards > 0]
  }
  pvec <- 1 - rowSums(pmat)
  Tstarmat <- matrix(rep(0,d^2), ncol = d)
  tstarvec <- rep(0,d)
  for(i in 1:d){
    for(j in (1:d)[-i]){
      Tstarmat[i,j] <- -subintensemat[i,i]/rewards[i]*pmat[i,j]
    }
    tstarvec[i] <- -subintensemat[i,i]/rewards[i]*pvec[i]
    Tstarmat[i,i] <- -sum(Tstarmat[i,])-tstarvec[i]
  }
  list("newinitprob" = alphavec, "newsubintensitymatrix" = Tstarmat, "defect" = 1 - sum(alphavec))
}
```

```{r}
time_function_call <- function(func, arg) {
  time <- proc.time()
  func(arg)
  (proc.time()-time)["elapsed"]
}

time_average <- function(func, setup_func, cleanup_func, repeats) {
  runs <- sapply(1:repeats, function(i) {
    res <- setup_func(i)
    ret <- time_function_call(func, res)
    cleanup_func(res)
    ret
  })
  
  list("avg" = mean(runs), "min" = min(runs), "max" = max(runs))
}
```


```{r time reward transformation}
PROP_TRANSITIONS = 0.01
N_STATES = NA
PROP_ZERO_REWARDS = NA
REPEATS = 1

max_transitions <- function(n_states) {
  N_STATES^2 - N_STATES
}

x <- seq(1000, 7000, by=1000)
r <- c(0.1, 0.5, 0.9)
times <- data.frame()

file_conn <- file("output.txt")

for (PROP_ZERO_REWARDS in r) {
for (N_STATES in x) {
  gen <- function(i) {
    seed <- 80002020 + i
    gen_c_mat(seed,
              N_STATES,
              max_transitions(N_STATES) * PROP_TRANSITIONS,
              N_STATES * PROP_ZERO_REWARDS)
  }
  
  gen_m <- function(i) {
    seed <- 80002020 + i
    gen_mat(seed,
              N_STATES,
              max_transitions(N_STATES) * PROP_TRANSITIONS,
              N_STATES * PROP_ZERO_REWARDS)
  }
  
  run <- function(graph) {
    reward_c_mat(graph);
  }
  
  run_m <- function(g) {
    rewardtransformparm(rewards=g$RW,initprob = g$IPV, subintensemat = g$SIM)
  }
  
  cleanup <- function(graph) {
    
  }
  
  time <- time_average(run, gen, cleanup, REPEATS);
  #time <- time_average(reward_test, gen_m, cleanup, REPEATS);
  
  times <- bind_rows(times, list(x = N_STATES,r=PROP_ZERO_REWARDS, avg = time$avg, min = time$min, max = time$max, type="CPP"))
  
 time <- time_average(run_m, gen_m, cleanup, REPEATS);
  
  times <- bind_rows(times, list(x = N_STATES, r=PROP_ZERO_REWARDS, avg = time$avg, min = time$min, max = time$max, type="R"))
  
  writeLines(as.character(times), file_conn)
  flush(file_conn)
}
}

close(file_conn)

```

```{r}
ggplot(times, aes(x=x,y=avg,color=type)) +
  geom_point() +
  geom_line() +
  facet_grid(vars(r)) +
  theme_bw()+
  labs(title = "Time spent reward transforming\nFacets are proportion of states with zero reward\nThe x-axis are the total number of states\nThe number of edges is 1% of all possible edges\n  i.e. (x*x-x)*0.01")+
  ggsave("plot.png", width=8, height=8)

```