// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "ptdalgorithms_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// graph_as_matrix
List graph_as_matrix(ptdalgorithms::Graph phase_type_graph);
RcppExport SEXP _ptdalgorithms_graph_as_matrix(SEXP phase_type_graphSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< ptdalgorithms::Graph >::type phase_type_graph(phase_type_graphSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_as_matrix(phase_type_graph));
    return rcpp_result_gen;
END_RCPP
}
// create_graph2
SEXP create_graph2(int state_length);
RcppExport SEXP _ptdalgorithms_create_graph2(SEXP state_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    int r = Rcpp::as<int >(state_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(create_graph2(r));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ptdalgorithms_graph_as_matrix", (DL_FUNC) &_ptdalgorithms_graph_as_matrix, 1},
    {"_ptdalgorithms_create_graph2", (DL_FUNC) &_ptdalgorithms_create_graph2, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ptdalgorithms(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
