// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// kingman_gen_mat
List kingman_gen_mat(int n, int m);
RcppExport SEXP _ptdalgorithms_kingman_gen_mat(SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(kingman_gen_mat(n, m));
    return rcpp_result_gen;
END_RCPP
}
// kingman_gen_reward
List kingman_gen_reward(int n, int r);
RcppExport SEXP _ptdalgorithms_kingman_gen_reward(SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(kingman_gen_reward(n, r));
    return rcpp_result_gen;
END_RCPP
}
// kingman_gen_reward_by
List kingman_gen_reward_by(int n, int m, Rcpp::Function reward_function);
RcppExport SEXP _ptdalgorithms_kingman_gen_reward_by(SEXP nSEXP, SEXP mSEXP, SEXP reward_functionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type reward_function(reward_functionSEXP);
    rcpp_result_gen = Rcpp::wrap(kingman_gen_reward_by(n, m, reward_function));
    return rcpp_result_gen;
END_RCPP
}
// kingman_exp_cov
List kingman_exp_cov(int n, int m);
RcppExport SEXP _ptdalgorithms_kingman_exp_cov(SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(kingman_exp_cov(n, m));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ptdalgorithms_kingman_gen_mat", (DL_FUNC) &_ptdalgorithms_kingman_gen_mat, 2},
    {"_ptdalgorithms_kingman_gen_reward", (DL_FUNC) &_ptdalgorithms_kingman_gen_reward, 2},
    {"_ptdalgorithms_kingman_gen_reward_by", (DL_FUNC) &_ptdalgorithms_kingman_gen_reward_by, 3},
    {"_ptdalgorithms_kingman_exp_cov", (DL_FUNC) &_ptdalgorithms_kingman_exp_cov, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ptdalgorithms(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
