# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

graph_as_matrix <- function(phase_type_graph) {
    .Call('_ptdalgorithms_graph_as_matrix', PACKAGE = 'ptdalgorithms', phase_type_graph)
}

matrix_as_graph <- function(initial_probability_vector, subintensity_matrix, rewards) {
    .Call('_ptdalgorithms_matrix_as_graph', PACKAGE = 'ptdalgorithms', initial_probability_vector, subintensity_matrix, rewards)
}

kingman_gen_graph <- function(n, m) {
    .Call('_ptdalgorithms_kingman_gen_graph', PACKAGE = 'ptdalgorithms', n, m)
}

reward_transform <- function(phase_type_graph, reward_function) {
    .Call('_ptdalgorithms_reward_transform', PACKAGE = 'ptdalgorithms', phase_type_graph, reward_function)
}

reward_transform_by_reward <- function(phase_type_graph, reward) {
    .Call('_ptdalgorithms_reward_transform_by_reward', PACKAGE = 'ptdalgorithms', phase_type_graph, reward)
}

graph_exp_cov <- function(phase_type_graph) {
    .Call('_ptdalgorithms_graph_exp_cov', PACKAGE = 'ptdalgorithms', phase_type_graph)
}

graph_info <- function(phase_type_graph) {
    .Call('_ptdalgorithms_graph_info', PACKAGE = 'ptdalgorithms', phase_type_graph)
}

