# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edges <- function(phase_type_vertex) {
    .Call(`_ptdalgorithms_edges`, phase_type_vertex)
}

create_graph <- function(state_length) {
    .Call(`_ptdalgorithms_create_graph`, state_length)
}

add_edge <- function(phase_type_vertex_from, phase_type_vertex_to, weight) {
    invisible(.Call(`_ptdalgorithms_add_edge`, phase_type_vertex_from, phase_type_vertex_to, weight))
}

create_vertex <- function(phase_type_graph, state) {
    .Call(`_ptdalgorithms_create_vertex`, phase_type_graph, state)
}

index_topological <- function(phase_type_graph) {
    invisible(.Call(`_ptdalgorithms_index_topological`, phase_type_graph))
}

index_invert <- function(phase_type_graph) {
    invisible(.Call(`_ptdalgorithms_index_invert`, phase_type_graph))
}

find_vertex <- function(phase_type_graph, state) {
    .Call(`_ptdalgorithms_find_vertex`, phase_type_graph, state)
}

find_or_create_vertex <- function(phase_type_graph, state) {
    .Call(`_ptdalgorithms_find_or_create_vertex`, phase_type_graph, state)
}

start_vertex <- function(phase_type_graph) {
    .Call(`_ptdalgorithms_start_vertex`, phase_type_graph)
}

graph_as_matrix <- function(phase_type_graph) {
    .Call(`_ptdalgorithms_graph_as_matrix`, phase_type_graph)
}

vertices_list <- function(phase_type_graph) {
    .Call(`_ptdalgorithms_vertices_list`, phase_type_graph)
}

list_has_next <- function(vertex_list) {
    .Call(`_ptdalgorithms_list_has_next`, vertex_list)
}

list_next <- function(vertex_list) {
    .Call(`_ptdalgorithms_list_next`, vertex_list)
}

